version: '3.5'

services:
  react-native-app:
    build: ./
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
